/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface CreditCard {
  balance: string;
  card_number: string;
  created_at: Date;
  id: Generated<number>;
  is_active: number;
  pin_hash: string;
  user_id: number;
}

export interface Transactions {
  amount: string;
  category: string;
  description: string;
  direction: "in" | "out";
  id: Generated<number>;
  receiver_account: string;
  receiver_user_id: Generated<number | null>;
  reciever_name: string;
  sender_account_id: number;
  timestamp: Date;
}

export interface Users {
  created_at: Date;
  email: string;
  id: Generated<number>;
  is_2fa_enabled: number;
  Name: string;
  password: string;
  role: string;
  two_fa_secret: string;
  user_profile_picture: string;
}

export interface DB {
  Credit_card: CreditCard;
  Transactions: Transactions;
  Users: Users;
}
